CFG = {
    "seed": 0,
    "device": {
        "use_cuda": True,
        "cuda_index": 0,
    },
    "paths": {
        "checkpoints_dir": "outputs/checkpoints",
        "predict_dir": "outputs/predictions",
    },
    "data": {
        "input_bands": 3,
        "class_num": 7,
        "source": {
            "image_dir": "datasets/LoveDA/Train/source/images",
            "mask_dir": "datasets/LoveDA/Train/source/masks",
        },
        "target": {
            "image_dir": "datasets/LoveDA/Train/target/images",
        },
        "target_val": {
            "image_dir": "datasets/LoveDA/Val/target/target_val_200/images",
            "mask_dir": "datasets/LoveDA/Val/target/target_val_200/masks",
        },
        "target_labeled_s3": {
            "image_dir": "datasets/LoveDA/Val/target/target_labeled_100/images",
            "mask_dir": "datasets/LoveDA/Val/target/target_labeled_100/masks",
        },
        "target_test": {
            "image_dir": "datasets/LoveDA/Val/target/target_test_692/images",
            "mask_dir": "datasets/LoveDA/Val/target/target_test_692/masks",
        },
        "source_val": {
            "image_dir": "datasets/LoveDA/Val/source/images",
            "mask_dir": "datasets/LoveDA/Val/source/masks",
        },
        "limit_images": None,
        "normalize": True,
    },
    "model": {
        "feature_dim": 128,
        "src_input_dim": 3,
        "tar_input_dim": 3,
        "n_dim": 32,
        "random_layer_dim": 1024,
        "e1_channels": 64,
    },
    "train": {
        "enable_uda": True,
        "learning_rate": 0.001,
        "max_epoch": 80,
        "best_model_metric": "miou",
        "da_lambda": 0.001,
        "stage1_epochs": 15,
        "stage2_warmup_epochs": 6,
        "s3_start_epoch": 16,
        "s3_warmup_epochs": 4,
        "s3_cc_lambda": 0.003,
        "enable_s3": True,
        "s3_align_mode": "target_labeled",
        "target_labeled_batch_size": 4,
        "s3_max_epochs": 50,
        "s3_stability_window": 3,
        "s3_stability_min_miou": 0.05,
        "s3_stability_max_std": 0.05,
        "pseudo_conf_start": 0.85,
        "pseudo_conf_end": 0.75,
        "pseudo_conf_decay_epochs": 20,
        "cc_min_pixels": 64,
        "use_all_source_samples": True,
        "sep_loss_weight": 1.0,
        "dice_loss_weight": 0.5,
        "focal_tversky_weight": 0.3,
        "focal_tversky_alpha": 0.3,
        "focal_tversky_beta": 0.7,
        "focal_tversky_gamma": 1.5,
        "gate_sparse_alpha": 0.01,
        "gate_excl_beta": 0.01,
        "source_batch_size": 4,
        "target_batch_size": 4,
        "class_weights": [0.55, 1.10, 2.80, 1.00, 0.90, 2.80, 0.90],
        "target_source_sup_weight": 0.0,
        "s3_target_sup_weight": 1.5,
        "ignore_index": 255,
        "foreground_aware_sampling": False,
        "foreground_class_index": 1,
        "fg_min_pixels_per_image": 1,
        "fg_per_batch": 1,
    },
    "eval": {
        "use_val": True,
        "val_batch_size": 1,
        "enable_iou": False,
        "predict_image_dir": "datasets/LoveDA/Val/target/target_test_692/images",
        "predict_batch_size": 1,
        "save_pred_masks": True,
    },
    "debug": {
        "enable_data_diagnostics": True,
        "batch_fg_ratio_batches": 0,
        "save_alignment_samples": False,
        "alignment_samples": 10,
    },
}
